# -*- coding: utf-8 -*-
"""project RT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtF2yhdxA0j09lrmpLsyjC2iZhqWozb7
"""

import streamlit as st
import pandas as pd
from datetime import datetime

# 1. Konfigurasi Halaman (Wide Layout)
st.set_page_config(page_title="Dashboard RT 05/02", layout="wide", initial_sidebar_state="expanded")

# 2. Injeksi Custom CSS untuk mempercantik tampilan
st.markdown("""
    <style>
    /* Styling untuk Container Kartu */
    div[data-testid="stMetricValue"] { font-size: 28px; font-weight: bold; color: #1E293B; }
    div[data-testid="stMetricLabel"] { font-size: 14px; color: #64748B; }

    /* Styling untuk list Pembayaran Terkini */
    .transaction-row {
        display: flex; align-items: center; justify-content: space-between;
        padding: 15px 0; border-bottom: 1px solid #F1F5F9;
    }
    .transaction-left { display: flex; align-items: center; gap: 15px; }
    .icon-box-in {
        background-color: #DCFCE7; color: #16A34A;
        width: 40px; height: 40px; border-radius: 50%;
        display: flex; align-items: center; justify-content: center; font-weight: bold;
    }
    .icon-box-out {
        background-color: #FEE2E2; color: #DC2626;
        width: 40px; height: 40px; border-radius: 50%;
        display: flex; align-items: center; justify-content: center; font-weight: bold;
    }
    .text-title { font-weight: 600; color: #0F172A; margin: 0; font-size: 15px;}
    .text-subtitle { color: #64748B; margin: 0; font-size: 13px;}
    .amount-in { color: #16A34A; font-weight: bold; }
    .amount-out { color: #DC2626; font-weight: bold; }
    </style>
""", unsafe_allow_html=True)

# 3. SIDEBAR: Menu Utama
with st.sidebar:
    st.markdown("<p style='color:#64748B; font-weight:bold; font-size:12px;'>MENU UTAMA</p>", unsafe_allow_html=True)
    # Menggunakan radio button agar berfungsi sebagai navigasi menu
    menu = st.radio(
        "Pilih Menu",
        ["Dashboard", "Keuangan & Kas", "Data Warga", "Agenda", "Aset & Sewa"],
        label_visibility="collapsed"
    )

# 4. AREA UTAMA: Header
if menu == "Dashboard":
    col_header1, col_header2 = st.columns([4, 1])
    with col_header1:
        st.markdown("<h2 style='margin-bottom: 0px; color:#0F172A;'>Ringkasan RT 05/02</h2>", unsafe_allow_html=True)
        st.markdown("<p style='color:#64748B; font-size:14px;'>Update terakhir: Hari ini, 09:00 WIB</p>", unsafe_allow_html=True)
    with col_header2:
        st.write("") # Spacer
        st.button("📥 Export Laporan", use_container_width=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # 5. KARTU RINGKASAN (3 Kolom)
    col1, col2, col3 = st.columns(3)

    with col1:
        with st.container(border=True):
            st.metric(label="Total Aset Kas", value="Rp 45.200.000")
            st.markdown("<span style='font-size:12px; background:#F1F5F9; padding:2px 8px; border-radius:4px;'>Ops: 12jt</span> <span style='font-size:12px; background:#F1F5F9; padding:2px 8px; border-radius:4px;'>Sosial: 33jt</span>", unsafe_allow_html=True)

    with col2:
        with st.container(border=True):
            st.metric(label="Iuran Januari", value="85%")
            st.progress(85)
            st.markdown("<p style='font-size:12px; color:#64748B; margin-top:5px;'>38 dari 45 KK sudah bayar</p>", unsafe_allow_html=True)

    with col3:
        with st.container(border=True):
            st.metric(label="Inventaris", value="2 Peminjaman")
            st.markdown("<p style='font-size:13px; color:#64748B; margin-top:10px;'>Tenda (Pak Budi), Kursi (Bu Siti)</p>", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # 6. PEMBAYARAN TERKINI
    with st.container(border=True):
        col_title, col_link = st.columns([4, 1])
        with col_title:
            st.markdown("<h4 style='color:#0F172A; margin:0;'>Pembayaran Terkini</h4>", unsafe_allow_html=True)
        with col_link:
            st.markdown("<div style='text-align:right;'><a href='#' style='color:#0D9488; text-decoration:none; font-size:14px; font-weight:600;'>Lihat Semua</a></div>", unsafe_allow_html=True)

        st.markdown("<hr style='margin:10px 0;'>", unsafe_allow_html=True)

        # Data Simulasi (Nanti bisa diganti dengan loop dari database Google Sheets)
        transactions = [
            {"type": "in", "title": "Iuran Kebersihan", "sub": "Bpk. Budi Pratama", "amount": "+ Rp 75.000"},
            {"type": "out", "title": "Perbaikan Lampu Jalan", "sub": "Pembelian material", "amount": "- Rp 150.000"},
            {"type": "in", "title": "Sewa Tenda (2 Set)", "sub": "Ibu Siti Aminah", "amount": "+ Rp 200.000"}
        ]

        # Merender list menggunakan HTML agar persis seperti gambar
        for tx in transactions:
            if tx['type'] == 'in':
                icon = "<div class='icon-box-in'>↙</div>"
                amount_class = "amount-in"
            else:
                icon = "<div class='icon-box-out'>↗</div>"
                amount_class = "amount-out"

            html_row = f"""
            <div class="transaction-row">
                <div class="transaction-left">
                    {icon}
                    <div>
                        <p class="text-title">{tx['title']}</p>
                        <p class="text-subtitle">{tx['sub']}</p>
                    </div>
                </div>
                <div class="{amount_class}">{tx['amount']}</div>
            </div>
            """
            st.markdown(html_row, unsafe_allow_html=True)

else:
    st.info(f"Halaman {menu} sedang dalam tahap pengembangan.")